import { Inter } from "next/font/google";
import { Kumbh_Sans } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";
import { UserProvider } from "./contexts/userContext";
const inter = Inter({ subsets: ["latin"] });
const kumbh = Kumbh_Sans({ subsets: ["latin"] });
export const metadata = {
  title: "Blife",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <body className={kumbh.className}>
          <Navbar />

          {children}
        </body>
      </html>
    </UserProvider>
  );
}
